os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project /Users/kshitij.gupta/Downloads/EssentialFeedClone/EssentialFeedClone.xcodeproj -scheme "CI" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO